name: General Store Automation workflow

on:
  [push, workflow_dispatch]

jobs:
  E2E:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Appium specific steps
    - name: Install Appium
      run: npm install -g appium

    - name: Start Appium Server
      run: appium &

    # Install Appium test framework and dependencies
    - name: Install Appium-Doctor
      run: npm install -g appium-doctor

    - name: Run Appium Tests
      run: appium-doctor

    - name: Clean and Compile
      run: mvn clean test

    - name: Stop Appium Server
      run: pkill -9 appium
