name: General Store Automation workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  E2E:
    runs-on: ubuntu-latest

    steps:
      - runs-on: macos-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-android@v2
          - name: Run Emulator
            uses: vgaidarji/android-github-actions-emulator@v1.0.1
            with:
              avd-name: my_avd

          # Set up JDK
          - name: Set up JDK
            uses: actions/setup-java@4.0.0 
            with:
              distribution: 'adopt'
              java-version: '21'

          # Install Node.js and npm
          - name: Install Node.js and npm
            uses: actions/setup-node@v4
            with:
              node-version: '20.10.0'

          # Install Appium dependencies
          - name: Install Appium dependencies
            run: |
              npm install -g appium@latest
              npm install -g appium-doctor@latest # Update as needed
              appium-doctor --android

          # Start Appium server
          - name: Start Appium server
            run: appium --log-level info &

          # Build and run Maven tests
          - name: Build and run Maven tests
            run: |
              mvn clean test
