name: General Store Automation workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  E2E:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Android SDK
        run: |
          # Download and extract the Android SDK tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip -q commandlinetools-linux-7583922_latest.zip -d cmdline-tools
          
          # Set up environment variables
          export ANDROID_HOME=$PWD/cmdline-tools
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools
          
          # Install SDK components using the new sdkmanager
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;31.0.0" "platforms;android-31"

      - name: Set Android Home
        run: export ANDROID_HOME=$PWD/cmdline-tools

      - name: Add ADB to Path
        run: export PATH=$PATH:$ANDROID_HOME/platform-tools

      - name: Start Appium server
        run: appium --log-level info &

      - name: Wait for Emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'

      - name: Reset ADB Server
        run: adb kill-server && adb start-server

      - name: Retry ADB Command
        run: adb shell getprop sys.boot_completed || adb shell getprop sys.boot_completed

      - name: Check ADB Devices
        run: adb devices

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          profile: Nexus 6
          arch: x86_64
          force-avd-creation: false
          avd-name: macOS-avd-arm64-v8a-31
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Build and run Maven tests
        run: |
          mvn clean test
