name: General Store Automation workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  E2E:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Android Emulator Runner Without SDK Setup
      #   uses: RandyLutcavich/android-emulator-runner-without-sdk-setup@v1.0.3
      #   with:
      #     api-level: 30

      # - name: Run Emulator
      #   uses: vgaidarji/android-github-actions-emulator@v1.0.1
      #   with:
      #     avd-name: my_avd
      #     api-level: 30

      # - name: Run Emulator
      #   uses: ReactiveCircus/android-emulator-runner@v2.29.0
      #   with:
      #     api-level: 31
      #     profile: Nexus 6
      #     arch: arm64-v8a
      #     force-avd-creation: false
      #     avd-name: macOS-avd-arm64-v8a-31
      #     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: true
      #     script: ./gradlew connectedCheck

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install Appium dependencies
        run: |
          npm install -g appium@latest
          npm install -g appium-doctor@latest
          appium-doctor --android

      - name: Start Appium server
        run: appium --log-level info &

      # - name: Wait for Emulator to start
      #   run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'

      - name: Reset ADB Server
        run: adb kill-server && adb start-server

      - name: Retry ADB Command
        run: adb shell getprop sys.boot_completed || adb shell getprop sys.boot_completed

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          profile: Nexus 6
          arch: x86_64
          force-avd-creation: false
          avd-name: macOS-avd-arm64-v8a-31
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Build and run Maven tests
        run: |
          mvn clean test
