name: General Store Automation workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  E2E:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Android Emulator Runner Without SDK Setup
        uses: RandyLutcavich/android-emulator-runner-without-sdk-setup@v1.0.3
        with:
          api-level: 30

      # - name: Run Emulator
      #   uses: vgaidarji/android-github-actions-emulator@v1.0.1
      #   with:
      #     avd-name: my_avd
      #     api-level: 30

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
            
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install Appium dependencies
        run: |
          npm install -g appium@latest
          npm install -g appium-doctor@latest # Update as needed
          appium-doctor --android

      - name: Start Appium server
        run: appium --log-level info &

      - name: Build and run Maven tests
        run: |
          mvn clean test
