name: General Store Automation workflow

on:
  [push, workflow_dispatch]

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      # Services
      - name: Emulator
        services:
          emulator:
            port-mappings:
              - 5555:5555
              - 5556:5556
              - 5037:5037
            options:
              --name: Nexus_5X_API_30_x86
              --device: "Nexus 5X"
              --resolution: 1080x1920

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # Install Node.js and npm
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Appium dependencies
      - name: Install Appium dependencies
        run: |
          npm install -g appium@latest
          npm install -g appium-doctor@latest # Update as needed
          appium-doctor --android

      # Start Appium server
      - name: Start Appium server
        run: appium --log-level info &

      # Build and run Maven tests
      - name: Build and run Maven tests
        run: |
          mvn clean test
