name: General Store Automation workflow

on:
  [push, workflow_dispatch]

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Appium Server Action
      uses: moatazeldebsy/Appium-Server-GitHub-Action@V1.0.7

    - name: Stop Appium Server
      run: pkill -9 appium
